version: '3.9'
services:
  backend: &backend-main
    build: ./Backend
    ports:
      - 5000-5001:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Host=db; Port=5432; Database=abstore; Username=abstore_rw; Password=1234
      - LISTENPORT=5000
    networks:
      - proxy-abstore-network
    deploy:
      replicas: 2

  backend-readonly: &backend-1
    <<: *backend-main
    ports:
      - 5002-5003:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Host=db; Port=5432; Database=abstore; Username=abstore_r; Password=1234
      - LISTENPORT=5000
    deploy:
      replicas: 2

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - BACKEND_SERVER=http://backend
  #   networks:
  #     - proxy-abstore-network
  #   stdin_open: true
  #   tty: true
    
  db:
    image: postgres
    ports:
      - "5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./sql/docker_create_db.sql:/docker-entrypoint-initdb.d/01.sql
      - ./sql/docker_fill_db.sql:/docker-entrypoint-initdb.d/02.sql
      - ./sql/docker_create_roles.sql:/docker-entrypoint-initdb.d/03.sql
      - ./sql/data:/var/db/data
    networks:
      - proxy-abstore-network
    environment:
      POSTGRES_USER: "abstore_user"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "abstore"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - proxy-abstore-network

networks:
  proxy-abstore-network:
    name: abstore-network
