\c abstore



--
-- USERS
--



CREATE TABLE public.users (
    id integer NOT NULL,
    username text NOT NULL,
    login text NOT NULL,
    password text NOT NULL,
    role text NOT NULL,
    created timestamp without time zone NOT NULL,
    last_changed timestamp without time zone NOT NULL
);

ALTER TABLE public.users OWNER TO abstore_user;

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "PK_users" PRIMARY KEY (id);

CREATE INDEX "IX_users_id" ON public.users USING btree (id);

CREATE UNIQUE INDEX "IX_users_login" ON public.users USING btree (login);

CREATE UNIQUE INDEX "IX_users_username" ON public.users USING btree (username);



--
-- PRODUCTS
--



CREATE TABLE public.products (
    id integer NOT NULL,
    symbol character(1) NOT NULL,
    price numeric NOT NULL,
    sale numeric NOT NULL,
    description text NOT NULL,
    created timestamp without time zone NOT NULL,
    last_changed timestamp without time zone NOT NULL
);

ALTER TABLE public.products OWNER TO abstore_user;

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "PK_products" PRIMARY KEY (id);

CREATE INDEX "IX_products_id" ON public.products USING btree (id);



--
-- ORDERS
--



CREATE TABLE public.orders (
    id integer NOT NULL,
    user_id integer NOT NULL,
    text text NOT NULL,
    price numeric NOT NULL,
    created timestamp without time zone NOT NULL,
    last_changed timestamp without time zone NOT NULL
);

ALTER TABLE public.orders OWNER TO abstore_user;

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT "PK_orders" PRIMARY KEY (id);

CREATE INDEX "IX_orders_id" ON public.orders USING btree (id);

CREATE INDEX "IX_orders_user_id" ON public.orders USING btree (user_id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT "FK_orders_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;



--
-- ORDERS_PRODUCTS
--



CREATE TABLE public.orders_products (
    id integer NOT NULL,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    qty integer NOT NULL,
    created timestamp without time zone NOT NULL,
    last_changed timestamp without time zone NOT NULL
);

ALTER TABLE public.orders_products OWNER TO abstore_user;

ALTER TABLE public.orders_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.orders_products
    ADD CONSTRAINT "PK_orders_products" PRIMARY KEY (id);

CREATE INDEX "IX_orders_products_id" ON public.orders_products USING btree (id);

CREATE UNIQUE INDEX "IX_orders_products_order_id_product_id" ON public.orders_products USING btree (order_id, product_id);

CREATE INDEX "IX_orders_products_product_id" ON public.orders_products USING btree (product_id);

ALTER TABLE ONLY public.orders_products
    ADD CONSTRAINT "FK_orders_products_orders_order_id" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.orders_products
    ADD CONSTRAINT "FK_orders_products_products_product_id" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


